### ISSUE TITLE
Why does this exist

### ISSUE THREAD

**Issue by wbhob** [tomarrell/rmraf#1]
This hurts to read. You can't play with people's hearts like this!

*Oh and someone will accidentally install it and destroy their machine.*

**Comment by tomarrell** [comment]
#2 I've added a clearer note to the top of the readme to make it as clear as possible that this can result in data loss.

I sincerely hope people read at least the intended functionality of the software before they run it freely on their own machine. At least in this case they've got to confirm that they know they're taking a risk.

And if all else fails a default 5/6 chance of walking out of it scott-free!  🎲 😄
